name: "Submit to Web Store"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --prefer-offline || npm ci
      - name: Build the extension
        run: npm run build
      - name: Package the extension
        run: cd build/chrome-mv3-prod && zip -r ../chrome-mv3-prod.zip .
      - name: Upload to Chrome Web Store
        env:
          CLIENT_ID: ${{ fromJson(secrets.SUBMIT_KEYS).chrome.clientId }}
          CLIENT_SECRET: ${{ fromJson(secrets.SUBMIT_KEYS).chrome.clientSecret }}
          REFRESH_TOKEN: ${{ fromJson(secrets.SUBMIT_KEYS).chrome.refreshToken }}
          EXTENSION_ID: ${{ fromJson(secrets.SUBMIT_KEYS).chrome.extId }}
          PUBLISHER_ID: e7af1311-0d51-4cfc-86d4-30d56516f806
        run: npx --yes chrome-webstore-upload-cli@latest upload --source build/chrome-mv3-prod.zip --extension-id $EXTENSION_ID --auto-publish
